version: '3'
services:
  mongo:
    image: 'mongo'
    container_name: 'mng_container'
    env_file:
      - variables.env
    ports:
      - "27016:27017"
    volumes:
      - mng_volume:/data/mgdb
    networks:
      - mongodb_nw
  flask:
    build:
      context: .
      dockerfile: './docker/Dockerfile.flask'
    container_name: 'flsk_cnt'
    env_file:
      - variables.env
    volumes:
      - .:/opt/services/forms_app
    networks:
      - web_nw
      - mongodb_nw
    depends_on:
      - mongo
  nginx:
    image: "nginx:1.13.5"
    container_name: 'ng_ctn'
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - web_nw
    depends_on:
      - flask
networks:
  web_nw:
    driver: bridge
  mongodb_nw:
    driver: bridge
volumes:
  form_app:
  mng_volume: